
CREATE TABLE IF NOT EXISTS chat_sessions(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 session_id TEXT UNIQUE,
 last_time DATETIME DEFAULT CURRENT_TIMESTAMP,
 email_sent INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS chats(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 session_id TEXT,
 role TEXT,
 content TEXT,
 created_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
