CREATE TABLE appointments(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
phone TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
phone TEXT UNIQUE,
email TEXT,
role TEXT DEFAULT 'member'
);

CREATE TABLE ai_messages(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
role TEXT,
content TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
