CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT,
password_hash TEXT
);

CREATE TABLE enterprises(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
plan TEXT
);

CREATE TABLE memberships(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
level TEXT
);

CREATE TABLE consultants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
status TEXT
);

CREATE TABLE ai_sessions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
content TEXT
);

CREATE TABLE orders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
amount REAL,
status TEXT
);