CREATE TABLE IF NOT EXISTS ai_reports(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
content TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments(
id INTEGER PRIMARY KEY AUTOINCREMENT,
order_id INTEGER,
amount REAL,
status TEXT
);

CREATE TABLE IF NOT EXISTS companies(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
plan TEXT
);

CREATE TABLE IF NOT EXISTS consultant_apply(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
specialty TEXT,
status TEXT
);