CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS members(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
level TEXT
);

CREATE TABLE IF NOT EXISTS bookings(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
service TEXT,
time TEXT
);

CREATE TABLE IF NOT EXISTS ai_sessions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
content TEXT
);

CREATE TABLE IF NOT EXISTS consultants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
status TEXT
);

CREATE TABLE IF NOT EXISTS companies(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);

CREATE TABLE IF NOT EXISTS crisis_records(
id INTEGER PRIMARY KEY AUTOINCREMENT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);