CREATE TABLE IF NOT EXISTS ai_messages(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
role TEXT,
content TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
plan TEXT,
status TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
specialty TEXT,
price INTEGER
);

CREATE TABLE IF NOT EXISTS test_reports(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
type TEXT,
score INTEGER,
report TEXT
);
