CREATE TABLE IF NOT EXISTS orders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
package TEXT,
amount REAL,
status TEXT
);

CREATE TABLE IF NOT EXISTS consultants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
specialty TEXT,
schedule TEXT
);

CREATE TABLE IF NOT EXISTS enterprises(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
contact TEXT,
plan TEXT
);

CREATE TABLE IF NOT EXISTS payments(
id INTEGER PRIMARY KEY AUTOINCREMENT,
order_id INTEGER,
amount REAL,
status TEXT
);