CREATE TABLE IF NOT EXISTS organizations(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
type TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);

CREATE TABLE IF NOT EXISTS permissions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
role_id INTEGER,
permission TEXT
);

CREATE TABLE IF NOT EXISTS doctor_schedule(
id INTEGER PRIMARY KEY AUTOINCREMENT,
doctor_id INTEGER,
schedule TEXT
);

CREATE TABLE IF NOT EXISTS subscriptions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
organization_id INTEGER,
plan TEXT,
status TEXT
);

CREATE TABLE IF NOT EXISTS audit_logs(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
action TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mental_profiles(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
summary TEXT,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
