CREATE TABLE IF NOT EXISTS organizations(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
type TEXT,
admin_id INTEGER,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);

CREATE TABLE IF NOT EXISTS permissions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
role_id INTEGER,
permission TEXT
);

CREATE TABLE IF NOT EXISTS doctor_profiles(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
specialty TEXT
);

CREATE TABLE IF NOT EXISTS mental_profiles(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
emotion TEXT,
stress_level INTEGER,
summary TEXT
);

CREATE TABLE IF NOT EXISTS company_reports(
id INTEGER PRIMARY KEY AUTOINCREMENT,
organization_id INTEGER,
report TEXT
);
