CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
phone TEXT,
level TEXT DEFAULT '普通会员'
);

CREATE TABLE IF NOT EXISTS ai_messages(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
role TEXT,
content TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
plan TEXT,
expire_time TEXT,
status TEXT
);

CREATE TABLE IF NOT EXISTS psych_tests(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
test_type TEXT,
score INTEGER,
result TEXT
);

CREATE TABLE IF NOT EXISTS consultants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
specialty TEXT
);
