CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT,
password_hash TEXT
);

CREATE TABLE IF NOT EXISTS orders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
amount REAL,
status TEXT
);

CREATE TABLE IF NOT EXISTS bookings(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
service TEXT,
time TEXT
);

CREATE TABLE IF NOT EXISTS consultants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
status TEXT
);

CREATE TABLE IF NOT EXISTS companies(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
plan TEXT
);

CREATE TABLE IF NOT EXISTS ai_sessions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
content TEXT
);