CREATE TABLE IF NOT EXISTS admin_users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE,
password TEXT,
role TEXT DEFAULT 'admin',
tenant_id INTEGER
);

CREATE TABLE IF NOT EXISTS tenants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
tenant_id INTEGER,
name TEXT,
status TEXT DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS permissions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
role TEXT,
permission TEXT
);
