CREATE TABLE IF NOT EXISTS admin_users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE,
password_hash TEXT,
role TEXT
);

CREATE TABLE IF NOT EXISTS admin_tokens(
id INTEGER PRIMARY KEY AUTOINCREMENT,
admin_id INTEGER,
token TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs(
id INTEGER PRIMARY KEY AUTOINCREMENT,
admin_id INTEGER,
action TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS company_staff(
id INTEGER PRIMARY KEY AUTOINCREMENT,
company_id INTEGER,
user_id INTEGER
);
