CREATE TABLE IF NOT EXISTS mental_records(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
content TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS risk_alerts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
level TEXT,
message TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_vectors(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT,
content TEXT
);

CREATE TABLE IF NOT EXISTS health_reports(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
report TEXT
);