CREATE TABLE IF NOT EXISTS admin_users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT,
password TEXT
);

CREATE TABLE IF NOT EXISTS ai_logs(
id INTEGER PRIMARY KEY AUTOINCREMENT,
message TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
