CREATE TABLE IF NOT EXISTS groups(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenants(
id INTEGER PRIMARY KEY AUTOINCREMENT,
group_id INTEGER,
name TEXT,
plan TEXT
);

CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
tenant_id INTEGER,
username TEXT
);

CREATE TABLE IF NOT EXISTS subscriptions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
tenant_id INTEGER,
plan TEXT,
status TEXT
);

CREATE TABLE IF NOT EXISTS ai_sessions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
content TEXT
);

CREATE TABLE IF NOT EXISTS orders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
tenant_id INTEGER,
amount REAL
);