CREATE TABLE IF NOT EXISTS appointments(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
phone TEXT,
type TEXT,
message TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_logs(
id INTEGER PRIMARY KEY AUTOINCREMENT,
message TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
